/* taylor Version 2.1, May 26, 2023 */
/* Using coef lib: MY_FLOAT */
/* Using jet lib: jet_1. n symbol, degree 1 */
#include "taylor_rho.h"

/***********************************************************************
 *
 * Code generated by the TAYLOR translator.
 */

#define _N_DIM_ 3
#define _J_DIM_ 3


#define xInitUpJet InitUpJet
#define xInitJet InitJet
#define xNormJet NormJet
#define xMultiplyFloatJetA MultiplyFloatJetA
#define xAddJetJetA AddJetJetA 
#define xAssignJetToJet AssignJetToJet
#define xAssignJetToFloat AssignJetToFloat





/*
next line defines the largest power of 2 such that 2^(LEXP2) and
2^(-LEXP2) do not overflow/underflow the double arithmetic of your
computer.
*/
#define LEXP2 1023 

#define DEBUG_LEVEL 0 /* to print some internal information */

int taylor_step_taylor_rho(MY_FLOAT *ti,
                 MY_FLOAT *x,
                 int      dir,
                 int      step_ctl,
                 double   log10abserr,
                 double   log10relerr,
                 MY_FLOAT *endtime,
                 MY_FLOAT *ht,
                 int      *order,
                 MY_JET   *jetInOut)
/*
 * single integration step with taylor method. the parameters are:
 *
 * ti: on input:  time of the initial condition
 *     on output: new time
 *
 * x:  on input:  initial condition
 *     on output: new condition, corresponding to the (output) time ti
 *
 * dir: flag to integrate forward or backwards.
 *     1: forward
 *    -1: backwards
 *     WARNING: this flag is ignored if step_ctl (see below) is set to 0.
 *
 * step_ctl: flag for the step size control. the possible values are:
 *     0: no step size control, so the step and order are provided by
 *        the user. the parameter ht is used as step, and the parameter
 *        order (see below) is used as the order.
 *     1: standard stepsize control. it uses an approximation to the
 *        optimal order and to the radius of convergence of the series
 *        to approximate the 'optimal' step size. It tries to keep
 *        either the absolute or the relative errors below the given
 *        values. See the paper for more details.
 *     2: as 1, but adding an extra condition on the stepsize h: the
 *        terms of the series --after being multiplied by the suitable
 *        power of h-- cannot grow.
 *    -1: user defined stepsize control. the code has to be included
 *        in the routine compute_timestep_user_defined (you can find
 *        this routine below). The user should also provide code for
 *        the selection of degree (see the function
 *        compute_order_user_defined below).
 *
 * log10abserr: decimal log of the absolute accuracy. the routine
 *     tries to keep either the absolute or the relative errors below
 *     the given thresholds.
 *
 * log10relerr: decimal log of the relative accuracy. the routine
 *     tries to keep either the absolute or the relative errors below
 *     the given thresholds.
 *
 * endtime: if NULL, it is ignored. if step_ctl (see above) is set
 *     to 0, it is also ignored. otherwise, if the step size is too
 *     large, it is reduced so that the new time ti is exactly endtime
 *     (in that case, the function returns 1).
 *
 * ht: on input:  ignored/used as a time step (see parameter step_ctl)
 *     on output: time step used if the pointer is not NULL
 *
 * order: degree of the taylor expansion.
 *        input: this parameter is only used if step_ctl is 0,
 *               or if you add the code for the case step_ctl=3.
 *               its possible values are:
 *               < 2: the program will select degree 2 (if step_ctl is 0).
 *               >=2: the program will use this degree (if step_ctl is 0).
 *        ouput: degree used if the pointer is not NULL
 *
 * jetInOut: on input: the value of all declared jet variables
 *           on output: new value of the jet variable, corresponding to the new time
 *
 * return value:
 *  0: ok.
 *  1: ok, and ti=endtime.  
 * -1: not ok, unable to compute step size.  double_log  underflow/overflow  */
{
  MY_FLOAT **taylor_coefficients_taylor_rho(MY_FLOAT, MY_FLOAT*, int);
  MY_FLOAT **taylor_coefficients_taylor_rhoA(MY_FLOAT, MY_FLOAT*, int, int);
  int compute_order_1_taylor_rho(double, double, double, int*);
  int comp_order_other_taylor_rho(double, double, double);
  double compute_stepsize_1_taylor_rho(MY_FLOAT**, MY_JET**, int, double, int);
  double compute_stepsize_2_taylor_rho(MY_FLOAT**, MY_JET**, int, double, int);
  double comp_stepsize_other_taylor_rho(MY_FLOAT**, MY_JET**, int, int, double, double, double);

  static MY_FLOAT **s,h,mtmp;
  static MY_JET jtmp,jtmp1, **jetJetOut;
  double xi,xnorm,dh;
  int i,j,k,nt,flag_endtime,flag_err;
  static int init=0;
#pragma omp threadprivate(s,h,mtmp,init)
#pragma omp threadprivate(jtmp,jtmp1,jetJetOut)

  if (init == 0) /* initialization of MY_FLOAT and MY_JET variables */
    {
      init=1;
      InitMyFloat(h);
      InitMyFloat(mtmp);
      xInitUpJet();
      xInitJet(jtmp);
      xInitJet(jtmp1);
    }
/*
  sup norm of the initial condition (jet included)
*/
  xnorm=0;
  if (step_ctl != 0)
    {
#if _J_DIM_ != 0
    for (i=0; i<_J_DIM_; i++)
      {
        xNormJet(mtmp,jetInOut[i]);
        MyFloatToDouble(xi,mtmp);
        xi=fabs(xi);
        if (xi > xnorm) xnorm=xi;
      }
#endif
      for (i=_J_DIM_; i<_N_DIM_; i++)
      {
        MyFloatToDouble(xi,x[i]);
        xi=fabs(xi);
        if (xi > xnorm) xnorm=xi;
      }
    }
/*
  we determine the degree of the taylor expansion.
  this value will be stored in the variable nt.
  the flag flag_err returns a value indicating if we are using an
  absolute error estimate (value 1) or a relative one (value 2).
*/
  switch(step_ctl)
    {
    case 0: /* no step size control, fixed degree; both given by the user */
      if (order==NULL)
      {
        fprintf(stderr,"step_ctl=%d needs an input order\n",step_ctl);
        exit(0);
      }
      nt=(*order<2)? 2: *order; /* 2 is the minimum order allowed */
      break;
    case 1:
      nt=compute_order_1_taylor_rho(xnorm,log10abserr,log10relerr,&flag_err);
      break;
    case 2:
      nt=compute_order_1_taylor_rho(xnorm,log10abserr,log10relerr,&flag_err);
      break;
    case -1:
      nt=comp_order_other_taylor_rho(xnorm,log10abserr,log10relerr);
      break;
    default:
      fprintf(stderr, "taylor_step: undefined step size control.\n");
      fprintf(stderr, "you must choose an existing step size control\n");
      fprintf(stderr, "method or supply a step size control procedure.\n");
      exit(0);
    }
  if (order!=NULL) *order=nt;
/*
  computation of the jet of derivatives up to order nt
*/
  if(step_ctl != 0) {
    s=taylor_coefficients_taylor_rho_A(*ti,x,nt,1, jetInOut, &jetJetOut);
  } else {
    s=taylor_coefficients_taylor_rho_A(*ti,x,nt,0, jetInOut, &jetJetOut); 
 }

/*
  selection of the routine to compute the time step. the value
  step_ctl=3 has been reserved for the user, in case she/he wants to
  code a different method.
*/
  dh=1.0;
  switch(step_ctl)
    {
    case 0: /* no step size control (fixed step size, given by the user) */
      if (ht==NULL)
      {
        fprintf(stderr,"step_ctl=%d needs an input stepsize\n",step_ctl);
        exit(0);
      }
      AssignMyFloat(h,*ht);
      break;
    case 1:
      dh=compute_stepsize_1_taylor_rho(s,jetJetOut,nt,xnorm,flag_err);
      MakeMyFloatA(h, dh);
      break;
    case 2:
      dh=compute_stepsize_2_taylor_rho(s,jetJetOut,nt,xnorm,flag_err);
      MakeMyFloatA(h, dh);
      break;
    case -1:
      dh=comp_stepsize_other_taylor_rho(s,jetJetOut,_N_DIM_,nt,xnorm,log10abserr,log10relerr);
      MakeMyFloatA(h, dh);
      break;
    default:
      fprintf(stderr, "taylor_step: undefined step size control.\n");
      fprintf(stderr, "You must choose an existing step size control\n");
      fprintf(stderr, "method or supply a step size control procedure.\n");
      exit(0);
    }
  if(dh == 0.0) return -1; //changeme
/*
  if step_ctl != 0, we adjust the sign of the computed stepsize.
*/
  flag_endtime=0;
  if (step_ctl != 0)
    {
      if (dir == -1) { NegateMyFloatA(mtmp,h); AssignMyFloat(h, mtmp);} 
/*
      we compare *ti+h with endtime. we modify h if necessary.
*/
      if (endtime != NULL)
        {
          AddMyFloatA(mtmp,h,*ti);
          if (dir == 1) /* time goes forward */
            {
              if (MyFloatA_GE_B(mtmp,*endtime))
                {
                  SubtractMyFloatA(h,*endtime,*ti);
                  flag_endtime=1;
                }
            }
            else /* time goes backwards */
            {
              if (MyFloatA_GE_B(*endtime,mtmp))
                {
                  SubtractMyFloatA(h,*endtime,*ti);
                  flag_endtime=1;
                }
            }
        }
    }
/*
  next lines are the summation of the taylor series (horner's method)
*/
  j=nt-1;
#if _J_DIM_ != 0
  for(i=0; i<_J_DIM_; i++)
  {
    xAssignJetToJet(jetInOut[i],jetJetOut[i][nt]);
    for(k=j; k>=0; k--)
    {
      xMultiplyFloatJetA(jtmp, h, jetInOut[i]);
      xAddJetJetA(jetInOut[i], jtmp, jetJetOut[i][k]);
    }
    xAssignJetToFloat(x[i],jetInOut[i]);
  }
#endif
  for(i=_J_DIM_; i<_N_DIM_; i++)
  {
    AssignMyFloat(x[i],s[i][nt]);
    for(k=j; k>=0; k--)
    {
      MultiplyMyFloatA(mtmp, h, x[i]);
      AddMyFloatA(x[i], mtmp, s[i][k]);
    }
  }
/*
  finally, we set the values of the parameters *ht and *ti.
*/
  if (ht!=NULL) AssignMyFloat(*ht,h);
  if (flag_endtime == 0)
    {
      AssignMyFloat(mtmp, *ti);
      AddMyFloatA(*ti, mtmp, h);
    }
    else
    {
      AssignMyFloat(*ti,*endtime);
    }
  return(flag_endtime);
}
int compute_order_1_taylor_rho(double xnorm, double log10abserr, double log10relerr, int* flag_err)
/*
 * this is to determine the 'optimal' degree of the taylor expansion.
 *
 * parameters:
 * xnorm: norm of the initial condition
 * log10abserr: base-10 log of the absolute error required
 * log10relerr: base-10 log of the relative error required
 * flag_err:    flag. returns 1 if absolute error is used
 *                    returns 2 if relative error is used
 *
 * returned value: 'optimal' degree.
*/
{
  double log10eps,tmp;
  int nt;

  log10eps=log10abserr;
  *flag_err=1;
  if (xnorm != (double)0.0)
    {
      tmp=log10relerr+log10(xnorm);
      if (tmp > log10abserr) {log10eps=log10relerr; *flag_err=2;}
    }
/*
  we use 1.16 for the value 0.5*log(10)=1.151292546497...
*/
  nt=(int)(1.5-1.16*log10eps);
  if (nt < 2) nt=2; /* this is the minimum order accepted */

#if DEBUG_LEVEL > 0
      fprintf(stderr, "taylor_step: order is %d\n",nt);
#endif

  return(nt);
}
double compute_stepsize_1_taylor_rho(MY_FLOAT **s, MY_JET **jet, int nt, double xnorm, int flag_err)
/*
 * it looks for a step size for an expansion up to order nt. this
 * function requires that nt is the value computed by
 * compute_order_1_
 */
{
  double double_log_MyFloat_taylor_rho(MY_FLOAT x);
  static MY_FLOAT z,v1,v2;
  static MY_FLOAT of,uf;
  double lnv1,lnv2,r,lnro1,lnro2,lnro;
  int i;
  static int init=0;
#pragma omp threadprivate(z,v1,v2,of,uf,init)

  if (init == 0)
    {
      init=1;
      InitMyFloat(z);
      InitMyFloat(v1);
      InitMyFloat(v2);
      InitMyFloat(of);
      InitMyFloat(uf);

      r=pow((double)2,(double)LEXP2);
      MakeMyFloatA(of,r);
      r=pow((double)2,(double)(-LEXP2));
      MakeMyFloatA(uf,r);
    }
/*
  we compute the sup norm of the last two coefficients of the taylor
  series, and we store them into v1 and v2.
*/
  MakeMyFloatA(v1,0);
  MakeMyFloatA(v2,0);
#if _J_DIM_ != 0
  for (i=0; i<_J_DIM_; i++)
  {
    xNormJet(z,jet[i][nt-1]);
    if (MyFloatA_GT_B(z,v1)) AssignMyFloat(v1,z);
    xNormJet(z,jet[i][nt]);
    if (MyFloatA_GT_B(z,v2)) AssignMyFloat(v2,z);
  }
#endif
  for(i=_J_DIM_; i<_N_DIM_; i++)
  {
    fabsMyFloatA(z,s[i][nt-1]);
    if (MyFloatA_GT_B(z,v1)) AssignMyFloat(v1,z);
    fabsMyFloatA(z,s[i][nt]);
    if (MyFloatA_GT_B(z,v2)) AssignMyFloat(v2,z);
  }
/*
  computation of the step size. we need the logs of v1 and v2, in
  double precision (there is no need for extended precision). the idea
  is to assign these variables to double variables and then to use the
  standard log function. before doing that, we have to be sure that v1
  can be assigned to a double without under or overflow. for this
  reason we will check for this condition and, if it fails, we will
  call an specific function for this case.
*/
  if (MyFloatA_LE_B(v1,of) && MyFloatA_GE_B(v1,uf))
    {
      MyFloatToDouble(r,v1);
      lnv1=log(r);
    }
    else
    {
      lnv1=double_log_MyFloat_taylor_rho(v1);
    }
  if (MyFloatA_LE_B(v2,of) && MyFloatA_GE_B(v2,uf))
    {
      MyFloatToDouble(r,v2);
      lnv2=log(r);
    }
    else
    {
      lnv2=double_log_MyFloat_taylor_rho(v2);
    }
  if(lnv1 == 65536.0 || lnv2 == 65536.0 ) return 0.0; //changeme
/*
  if flag_err == 2, this means that we are using a relative error control.
*/
  if (flag_err == 2)
    {
      r = -log10(xnorm);
      lnv1 += r;
      lnv2 += r;
    }
 lnro1= -lnv1/(nt-1);
 lnro2= -lnv2/nt;
 lnro=(lnro1 < lnro2)? lnro1: lnro2;

 r=exp(lnro-2-0.7/(nt-1)); /* exp(-0.7/(nt-1)) is a security factor */
  return(r);
}
double compute_stepsize_2_taylor_rho(MY_FLOAT **s, MY_JET **jet, int nt, double xnorm, int flag_err)
/*
 * it looks for a step size for an expansion up to order nt. this
 * function requires that nt is the value computed by
 * compute_order_1_. it also tries to reduce cancellations of big
 * terms in the summation of the taylor series.
 */
{
  double compute_stepsize_1_taylor_rho(MY_FLOAT**, MY_JET**, int, double, int);
  static MY_FLOAT h,hj,r,z,a,normj;
  double c,rtmp,dh;
  int i,j;
  static int init=0;
#pragma omp threadprivate(h,hj,r,z,a,normj,init)

  if (init == 0)
    {
      init=1;
      InitMyFloat(h); 
      InitMyFloat(hj);
      InitMyFloat(r);
      InitMyFloat(z);
      InitMyFloat(a);
      InitMyFloat(normj);
    }
/*
  we compute the step size according to the first algorithm
*/
  dh=compute_stepsize_1_taylor_rho(s,jet,nt,xnorm,flag_err);
  if(dh == 0.0) return  0.0; // changeme
  MakeMyFloatA(h,dh);
/*
  next lines select a value (z), that will be used to control the size
  of the terms of the Taylor series.
*/
  if (flag_err == 1) {
     MakeMyFloatA(z, 1.0);
  } else if (flag_err == 2) {
    MakeMyFloatA(z,xnorm);
  } else
    {
      printf("compute_stepsize_2 internal error. flag_err: %d\n",flag_err);
      exit(1);
    }
/*
  next loop checks if the sup norm of the terms in the Taylor series are
  lower than z. if a term is greater than z, the step size h is reduced.
*/
  MakeMyFloatA(hj,(double)1.0);

  for(j=1; j<=nt; j++)
  {
    MultiplyMyFloatA(r,h,hj);
    AssignMyFloat(hj,r);

    MakeMyFloatC(normj,"0", (double)0);
#if _J_DIM_ != 0
    for (i=0; i<_J_DIM_; i++)
    {
      xNormJet(a,jet[i][j]);
      if (MyFloatA_GT_B(a,normj)) AssignMyFloat(normj,a);
    }
#endif
    for (i=_J_DIM_; i<_N_DIM_; i++)
    {
      fabsMyFloatA(a,s[i][j]);
      if (MyFloatA_GT_B(a,normj)) AssignMyFloat(normj,a);
    }

    MultiplyMyFloatA(r,normj,hj);
    if (MyFloatA_LE_B(r,z)) continue;
/*
    we reduce h (and hj)
*/
    DivideMyFloatA(hj,z,normj);

    DivideMyFloatA(a,r,z);
    MyFloatToDouble(c,a);
    c=pow(c,(double)1.e0/(double)j);
    MakeMyFloatA(a,c);
    DivideMyFloatA(r,h,a);
    AssignMyFloat(h,r);

#if DEBUG_LEVEL > 1
    fprintf(stderr, "order %2d. reducing h from %14.6e to %14.6e\n",j,c*h,h);
#endif
  }

  MyFloatToDouble(rtmp,h);
  return(rtmp);
}

double double_log_MyFloat_taylor_rho(MY_FLOAT x)
/*
 * natural log, in double precision, of a MY_FLOAT positive number.
 */
{
  static MY_FLOAT a,tmp;
  static MY_FLOAT z,of,uf;
  double b,lx;
  int k;
  static int init=0;
#pragma omp threadprivate(a,tmp,z,of,uf,init)

  if (init == 0)
    {
      init=1;
      InitMyFloat(a);
      InitMyFloat(z);
      InitMyFloat(of);
      InitMyFloat(uf);
      InitMyFloat(tmp);

      b=0;
      MakeMyFloatA(z,b);
      b=pow((double)2,(double)LEXP2);
      MakeMyFloatA(of,b);
      b=pow((double)2,(double)(-LEXP2));
      MakeMyFloatA(uf,b);
    }

  if (MyFloatA_EQ_B(x,z))
    {
      puts("double_log_MyFloat error: zero argument");
      puts("(this is because one of the last two terms of your taylor");
      puts(" expansion is exactly zero)");
      /*exit(1);*/
      return 65536.0;
    }

  AssignMyFloat(a,x);

  k=0;
  while(MyFloatA_LT_B(a,uf))
  {
    ++k;
    if(k>3000){fprintf(stderr,"double_log_MyFloat overflow: %d\n", k); /*exit(1);*/ return 65536.0;}
     MultiplyMyFloatA(tmp,a,of);
    AssignMyFloat(a,tmp);
  }
  while(MyFloatA_GT_B(a,of))
  {
    --k;
    if(k<-3000){fprintf(stderr,"double_log_MyFloat underflow: %d\n", k); /*exit(1);*/ return 65536.0;}
     MultiplyMyFloatA(tmp,a,uf);
    AssignMyFloat(a,tmp);
  }

  MyFloatToDouble(b,a);
/*
  lx stands for log(x)
*/
  lx=log(b)-(LEXP2*0.69314718055994530942)*k;

  return(lx);
}


int comp_order_other_taylor_rho(double lnxnorm, double log10abserr, double log10relerr){
  puts("---");
  puts("compute_order_user_defined:");
  puts("you have to code this routine");
  puts("or select a different value for the step_ctl parameter");
  puts("---");
  exit(1);

  return(0);
}
double comp_stepsize_other_taylor_rho(MY_FLOAT **s, MY_JET **jet, int nd, int nt, double xnorm, double log10abserr, double log10relerr) {

  puts("---");
  puts("compute_timestep_user_defined:");
  puts("you have to code this routine");
  puts("or select a different value for the step_ctl parameter");
  puts("---");
  exit(1);
  return((double)0.00001);
}
static int _jet_1_monomial_counts_taylor_rho_[]  =      {1,3};
static int _jet_1_monomial_offsets_taylor_rho_[] =      {0,1,4};
/* MACROS TO LINK MY_FLOAT WITH MY_JET COEFFICIENTS */
#ifndef myfloat_t
#define myfloat_t          MY_FLOAT

#define myfloat_init       InitMyFloat
#define myfloat_clean      ClearMyFloat

/* assign */
#define myfloat_set        AssignMyFloat
#define myfloat_set_d      MakeMyFloatB
#define myfloat_set_si     MakeMyFloatB
#define myfloat_set_zero(r) MakeMyFloatC(r,"0",0)

/* elemental operations */
#define myfloat_add2       AddMyFloatA
#define myfloat_sub2       SubtractMyFloatA
#define myfloat_mul2       MultiplyMyFloatA
#define myfloat_div2       DivideMyFloatA

#define myfloat_add2_d     AddMyFloatD
#define myfloat_sub2_d     SubtractMyFloatD
#define myfloat_mul2_d     MultiplyMyFloatD
#define myfloat_div2_d     DivideMyFloatD
#define myfloat_d_sub2     SubtractDMyFloat
#define myfloat_d_div2     DivideDMyFloat

#define myfloat_add2_si    AddMyFloatSI
#define myfloat_sub2_si    SubtractMyFloatSI
#define myfloat_mul2_si    MultiplyMyFloatSI
#define myfloat_div2_si    DivideMyFloatSI
#define myfloat_si_sub2    SubtractSIMyFloat
#define myfloat_si_div2    DivideSIMyFloat

#define myfloat_neg        NegateMyFloatA

/* built-in functions */
#define myfloat_set_sqrt   sqrtMyFloatA
#define myfloat_set_pow    ExponentiateMyFloatA
#define myfloat_set_pow_si ExponentiateMyFloatIA

#define myfloat_set_sin    sinMyFloatA
#define myfloat_set_cos    cosMyFloatA
#define myfloat_set_tan    tanMyFloatA
#define myfloat_set_atan   atanMyFloatA
#define myfloat_set_exp    expMyFloatA
#define myfloat_set_log    logMyFloatA
#define myfloat_set_sinh   sinhMyFloatA
#define myfloat_set_cosh   coshMyFloatA
#define myfloat_set_tanh   tanhMyFloatA
#define myfloat_set_log10  log10MyFloatA
#define myfloat_set_fabs   fabsMyFloatA
#define myfloat_to_si      MyFloatToInt
#define myfloat_to_d       MyFloatToDouble

/* boolean operations */
#define myfloat_ge  MyFloatA_GE_B
#define myfloat_gt  MyFloatA_GT_B
#define myfloat_le  MyFloatA_LE_B
#define myfloat_lt  MyFloatA_LT_B
#define myfloat_eq  MyFloatA_EQ_B
#define myfloat_neq MyFloatA_NEQ_B

/* output format */
#define myfloat_fprintf OutputMyFloat3

/* input format */
#define myfloat_fscanf InputMyFloat3
#endif /* END myfloat_t */


/* BEGIN PRECODE mycoef_myfloat_t_taylor_rho */
#define mycoef_myfloat_t_taylor_rho          MY_COEF
/* END PRECODE mycoef_myfloat_t_taylor_rho */


/* BEGIN MY_COEF_MY_FLOAT_BASIC mycoef_myfloat_t_taylor_rho */
#define mycoef_myfloat_initup2_taylor_rho(s,d)    
#define mycoef_myfloat_initup_taylor_rho()        
#define mycoef_myfloat_init_taylor_rho            InitMyFloat
#define mycoef_myfloat_clean_taylor_rho           ClearMyFloat
#define mycoef_myfloat_cleanup_taylor_rho()       

/* assign */
#define mycoef_myfloat_set_taylor_rho             AssignMyFloat
#define mycoef_myfloat_set_myfloat_taylor_rho     AssignMyFloat
#define mycoef_myfloat_set_d_taylor_rho           MakeMyFloatB
#define mycoef_myfloat_set_si_taylor_rho          MakeMyFloatB
#define mycoef_myfloat_set_zero_taylor_rho(r)     MakeMyFloatC(r,"0",0)

/* elemental operations */
#define mycoef_myfloat_add2_taylor_rho            AddMyFloatA
#define mycoef_myfloat_sub2_taylor_rho            SubtractMyFloatA
#define mycoef_myfloat_mul2_taylor_rho            MultiplyMyFloatA
#define mycoef_myfloat_div2_taylor_rho            DivideMyFloatA

#define mycoef_myfloat_add2_myfloat_taylor_rho    AddMyFloatA
#define mycoef_myfloat_sub2_myfloat_taylor_rho    SubtractMyFloatA
#define mycoef_myfloat_mul2_myfloat_taylor_rho    MultiplyMyFloatA
#define mycoef_myfloat_div2_myfloat_taylor_rho    DivideMyFloatA
#define mycoef_myfloat_myfloat_sub2_taylor_rho    SubtractMyFloatA
#define mycoef_myfloat_myfloat_div2_taylor_rho    DivideMyFloatA

#define mycoef_myfloat_add2_d_taylor_rho          AddMyFloatD
#define mycoef_myfloat_sub2_d_taylor_rho          SubtractMyFloatD
#define mycoef_myfloat_mul2_d_taylor_rho          MultiplyMyFloatD
#define mycoef_myfloat_div2_d_taylor_rho          DivideMyFloatD
#define mycoef_myfloat_d_sub2_taylor_rho          SubtractDMyFloat
#define mycoef_myfloat_d_div2_taylor_rho          DivideDMyFloat

#define mycoef_myfloat_add2_si_taylor_rho         AddMyFloatSI
#define mycoef_myfloat_sub2_si_taylor_rho         SubtractMyFloatSI
#define mycoef_myfloat_mul2_si_taylor_rho         MultiplyMyFloatSI
#define mycoef_myfloat_div2_si_taylor_rho         DivideMyFloatSI
#define mycoef_myfloat_si_sub2_taylor_rho         SubtractSIMyFloat
#define mycoef_myfloat_si_div2_taylor_rho         DivideSIMyFloat

#define mycoef_myfloat_neg_taylor_rho             NegateMyFloatA

/* built-in functions */
#define mycoef_myfloat_set_sqrt_taylor_rho        sqrtMyFloatA
#define mycoef_myfloat_set_pow_myfloat_taylor_rho ExponentiateMyFloatA
#define mycoef_myfloat_set_pow_si_taylor_rho      ExponentiateMyFloatIA

#define mycoef_myfloat_set_sin_taylor_rho         sinMyFloatA
#define mycoef_myfloat_set_cos_taylor_rho         cosMyFloatA
#define mycoef_myfloat_set_tan_taylor_rho         tanMyFloatA
#define mycoef_myfloat_set_atan_taylor_rho        atanMyFloatA
#define mycoef_myfloat_set_exp_taylor_rho         expMyFloatA
#define mycoef_myfloat_set_log_taylor_rho         logMyFloatA
#define mycoef_myfloat_set_sinh_taylor_rho        sinhMyFloatA
#define mycoef_myfloat_set_cosh_taylor_rho        coshMyFloatA
#define mycoef_myfloat_set_tanh_taylor_rho        tanhMyFloatA
#define mycoef_myfloat_set_log10_taylor_rho       log10MyFloatA
#define mycoef_myfloat_set_fabs_taylor_rho        fabsMyFloatA

/* castings */
#define mycoef_myfloat_to_myfloat_taylor_rho(a)   &(a)
#define mycoef_myfloat_to_si_taylor_rho           MyFloatToInt
#define mycoef_myfloat_to_d_taylor_rho            MyFloatToDouble

/* boolean operations */
#define mycoef_myfloat_ge_taylor_rho  MyFloatA_GE_B
#define mycoef_myfloat_gt_taylor_rho  MyFloatA_GT_B
#define mycoef_myfloat_le_taylor_rho  MyFloatA_LE_B
#define mycoef_myfloat_lt_taylor_rho  MyFloatA_LT_B
#define mycoef_myfloat_eq_taylor_rho  MyFloatA_EQ_B
#define mycoef_myfloat_neq_taylor_rho MyFloatA_NEQ_B

/* norms */
#define mycoef_myfloat_nrminf_taylor_rho(a,b) mycoef_myfloat_set_fabs_taylor_rho(*(a),b)
#define mycoef_myfloat_nrm2_taylor_rho(a,b) mycoef_myfloat_mul2_taylor_rho(*(a),b,b)

/* output format */
#define mycoef_myfloat_fprintf_taylor_rho OutputMyFloat3

/* input format */
#define mycoef_myfloat_fscanf_taylor_rho InputMyFloat3

/* string scanf */
#define mycoef_myfloat_sscanf4_taylor_rho StringToMyFloat4
/* END MY_COEF_MY_FLOAT_BASIC mycoef_myfloat_t_taylor_rho */


/* BEGIN MY_COEF_MY_FLOAT_BASIC mycoef_myfloat_t_taylor_rho */
#define mycoef_myfloat_initup2_taylor_rho(s,d)    
#define mycoef_myfloat_initup_taylor_rho()        
#define mycoef_myfloat_init_taylor_rho            InitMyFloat
#define mycoef_myfloat_clean_taylor_rho           ClearMyFloat
#define mycoef_myfloat_cleanup_taylor_rho()       

/* assign */
#define mycoef_myfloat_set_taylor_rho             AssignMyFloat
#define mycoef_myfloat_set_myfloat_taylor_rho     AssignMyFloat
#define mycoef_myfloat_set_d_taylor_rho           MakeMyFloatB
#define mycoef_myfloat_set_si_taylor_rho          MakeMyFloatB
#define mycoef_myfloat_set_zero_taylor_rho(r)     MakeMyFloatC(r,"0",0)

/* elemental operations */
#define mycoef_myfloat_add2_taylor_rho            AddMyFloatA
#define mycoef_myfloat_sub2_taylor_rho            SubtractMyFloatA
#define mycoef_myfloat_mul2_taylor_rho            MultiplyMyFloatA
#define mycoef_myfloat_div2_taylor_rho            DivideMyFloatA

#define mycoef_myfloat_add2_myfloat_taylor_rho    AddMyFloatA
#define mycoef_myfloat_sub2_myfloat_taylor_rho    SubtractMyFloatA
#define mycoef_myfloat_mul2_myfloat_taylor_rho    MultiplyMyFloatA
#define mycoef_myfloat_div2_myfloat_taylor_rho    DivideMyFloatA
#define mycoef_myfloat_myfloat_sub2_taylor_rho    SubtractMyFloatA
#define mycoef_myfloat_myfloat_div2_taylor_rho    DivideMyFloatA

#define mycoef_myfloat_add2_d_taylor_rho          AddMyFloatD
#define mycoef_myfloat_sub2_d_taylor_rho          SubtractMyFloatD
#define mycoef_myfloat_mul2_d_taylor_rho          MultiplyMyFloatD
#define mycoef_myfloat_div2_d_taylor_rho          DivideMyFloatD
#define mycoef_myfloat_d_sub2_taylor_rho          SubtractDMyFloat
#define mycoef_myfloat_d_div2_taylor_rho          DivideDMyFloat

#define mycoef_myfloat_add2_si_taylor_rho         AddMyFloatSI
#define mycoef_myfloat_sub2_si_taylor_rho         SubtractMyFloatSI
#define mycoef_myfloat_mul2_si_taylor_rho         MultiplyMyFloatSI
#define mycoef_myfloat_div2_si_taylor_rho         DivideMyFloatSI
#define mycoef_myfloat_si_sub2_taylor_rho         SubtractSIMyFloat
#define mycoef_myfloat_si_div2_taylor_rho         DivideSIMyFloat

#define mycoef_myfloat_neg_taylor_rho             NegateMyFloatA

/* built-in functions */
#define mycoef_myfloat_set_sqrt_taylor_rho        sqrtMyFloatA
#define mycoef_myfloat_set_pow_myfloat_taylor_rho ExponentiateMyFloatA
#define mycoef_myfloat_set_pow_si_taylor_rho      ExponentiateMyFloatIA

#define mycoef_myfloat_set_sin_taylor_rho         sinMyFloatA
#define mycoef_myfloat_set_cos_taylor_rho         cosMyFloatA
#define mycoef_myfloat_set_tan_taylor_rho         tanMyFloatA
#define mycoef_myfloat_set_atan_taylor_rho        atanMyFloatA
#define mycoef_myfloat_set_exp_taylor_rho         expMyFloatA
#define mycoef_myfloat_set_log_taylor_rho         logMyFloatA
#define mycoef_myfloat_set_sinh_taylor_rho        sinhMyFloatA
#define mycoef_myfloat_set_cosh_taylor_rho        coshMyFloatA
#define mycoef_myfloat_set_tanh_taylor_rho        tanhMyFloatA
#define mycoef_myfloat_set_log10_taylor_rho       log10MyFloatA
#define mycoef_myfloat_set_fabs_taylor_rho        fabsMyFloatA

/* castings */
#define mycoef_myfloat_to_myfloat_taylor_rho(a)   &(a)
#define mycoef_myfloat_to_si_taylor_rho           MyFloatToInt
#define mycoef_myfloat_to_d_taylor_rho            MyFloatToDouble

/* boolean operations */
#define mycoef_myfloat_ge_taylor_rho  MyFloatA_GE_B
#define mycoef_myfloat_gt_taylor_rho  MyFloatA_GT_B
#define mycoef_myfloat_le_taylor_rho  MyFloatA_LE_B
#define mycoef_myfloat_lt_taylor_rho  MyFloatA_LT_B
#define mycoef_myfloat_eq_taylor_rho  MyFloatA_EQ_B
#define mycoef_myfloat_neq_taylor_rho MyFloatA_NEQ_B

/* norms */
#define mycoef_myfloat_nrminf_taylor_rho(a,b) mycoef_myfloat_set_fabs_taylor_rho(*(a),b)
#define mycoef_myfloat_nrm2_taylor_rho(a,b) mycoef_myfloat_mul2_taylor_rho(*(a),b,b)

/* output format */
#define mycoef_myfloat_fprintf_taylor_rho OutputMyFloat3

/* input format */
#define mycoef_myfloat_fscanf_taylor_rho InputMyFloat3

/* string scanf */
#define mycoef_myfloat_sscanf4_taylor_rho StringToMyFloat4
/* END MY_COEF_MY_FLOAT_BASIC mycoef_myfloat_t_taylor_rho */


/* BEGIN MY_COEF_MY_FLOAT_POSTCODE mycoef_myfloat_t_taylor_rho */
/* MACROS TO LINK MY_COEF */
#ifndef mycoef_t 
#define mycoef_t mycoef_myfloat_t_taylor_rho

#define mycoef_initup() mycoef_myfloat_initup2_taylor_rho(_MY_COEF_MAX_NUM_SYMBOLS_,_MY_COEF_MAX_DEGREE_)
#define mycoef_init(a)  mycoef_myfloat_init_taylor_rho((a))
#define mycoef_clean(a) mycoef_myfloat_clean_taylor_rho((a))
#define mycoef_cleanup  mycoef_myfloat_cleanup_taylor_rho

/* norm functions */
#define mycoef_nrminf mycoef_myfloat_nrminf_taylor_rho
#define mycoef_nrm2 mycoef_myfloat_nrm2_taylor_rho

/* casts */
#define mycoef_to_myfloat mycoef_myfloat_to_myfloat_taylor_rho

/* assign */
#define mycoef_set mycoef_myfloat_set_taylor_rho
#define mycoef_set_zero mycoef_myfloat_set_zero_taylor_rho
#define mycoef_set_myfloat mycoef_myfloat_set_myfloat_taylor_rho
#define mycoef_set_d mycoef_myfloat_set_d_taylor_rho
#define mycoef_set_si mycoef_myfloat_set_si_taylor_rho

/* elemental operations */
#define mycoef_add2 mycoef_myfloat_add2_taylor_rho
#define mycoef_sub2 mycoef_myfloat_sub2_taylor_rho
#define mycoef_mul2 mycoef_myfloat_mul2_taylor_rho
#define mycoef_div2 mycoef_myfloat_div2_taylor_rho

#define mycoef_add2_myfloat mycoef_myfloat_add2_myfloat_taylor_rho
#define mycoef_sub2_myfloat mycoef_myfloat_sub2_myfloat_taylor_rho
#define mycoef_myfloat_sub2 mycoef_myfloat_myfloat_sub2_taylor_rho
#define mycoef_mul2_myfloat mycoef_myfloat_mul2_myfloat_taylor_rho
#define mycoef_div2_myfloat mycoef_myfloat_div2_myfloat_taylor_rho
#define mycoef_myfloat_div2 mycoef_myfloat_myfloat_div2_taylor_rho

#define mycoef_add2_d mycoef_myfloat_add2_d_taylor_rho
#define mycoef_sub2_d mycoef_myfloat_sub2_d_taylor_rho
#define mycoef_mul2_d mycoef_myfloat_mul2_d_taylor_rho
#define mycoef_div2_d mycoef_myfloat_div2_d_taylor_rho
#define mycoef_d_sub2 mycoef_myfloat_d_sub2_taylor_rho
#define mycoef_d_div2 mycoef_myfloat_d_div2_taylor_rho

#define mycoef_add2_si mycoef_myfloat_add2_si_taylor_rho
#define mycoef_sub2_si mycoef_myfloat_sub2_si_taylor_rho
#define mycoef_mul2_si mycoef_myfloat_mul2_si_taylor_rho
#define mycoef_div2_si mycoef_myfloat_div2_si_taylor_rho
#define mycoef_si_sub2 mycoef_myfloat_si_sub2_taylor_rho
#define mycoef_si_div2 mycoef_myfloat_si_div2_taylor_rho

#define mycoef_neg mycoef_myfloat_neg_taylor_rho

/* built-in functions */
#define mycoef_set_sqrt mycoef_myfloat_set_sqrt_taylor_rho
#define mycoef_set_pow_myfloat mycoef_myfloat_set_pow_myfloat_taylor_rho
#define mycoef_set_pow_si mycoef_myfloat_set_pow_si_taylor_rho

#define mycoef_set_sin mycoef_myfloat_set_sin_taylor_rho
#define mycoef_set_cos mycoef_myfloat_set_cos_taylor_rho
#define mycoef_set_tan mycoef_myfloat_set_tan_taylor_rho
#define mycoef_set_atan mycoef_myfloat_set_atan_taylor_rho
#define mycoef_set_exp mycoef_myfloat_set_exp_taylor_rho
#define mycoef_set_log mycoef_myfloat_set_log_taylor_rho
#define mycoef_set_sinh mycoef_myfloat_set_sinh_taylor_rho
#define mycoef_set_cosh mycoef_myfloat_set_cosh_taylor_rho
#define mycoef_set_tanh mycoef_myfloat_set_tanh_taylor_rho
#define mycoef_set_log10 mycoef_myfloat_set_log10_taylor_rho
#define mycoef_set_fabs mycoef_myfloat_set_fabs_taylor_rho

/* castings */
#define mycoef_to_si mycoef_myfloat_to_si_taylor_rho
#define mycoef_to_d mycoef_myfloat_to_d_taylor_rho

/* boolean operations */
#define mycoef_ge mycoef_myfloat_ge_taylor_rho
#define mycoef_gt mycoef_myfloat_gt_taylor_rho
#define mycoef_le mycoef_myfloat_le_taylor_rho
#define mycoef_lt mycoef_myfloat_lt_taylor_rho
#define mycoef_eq mycoef_myfloat_eq_taylor_rho
#define mycoef_neq mycoef_myfloat_neq_taylor_rho

/* output format */
#define mycoef_fprintf mycoef_myfloat_fprintf_taylor_rho

/* input format */
#define mycoef_fscanf mycoef_myfloat_fscanf_taylor_rho

/* string scanf */
#define mycoef_sscanf4 mycoef_myfloat_sscanf4_taylor_rho
#endif /* END my_coef_t */

 
/* END MY_COEF_MY_FLOAT_POSTCODE mycoef_myfloat_t_taylor_rho */

/* MACROS TO LINK MY_COEF */
#ifndef mycoef_t 
#define mycoef_t mycoef_t

#define mycoef_initup() mycoef_initup2(_NUMBER_OF_MAX_SYMBOLS_,_MAX_DEGREE_OF_JET_VARS_)
#define mycoef_init(a)  mycoef_init(&(a))
#define mycoef_clean(a) mycoef_clean(&(a))
#define mycoef_cleanup  mycoef_cleanup

/* norm functions */
#define mycoef_nrminf mycoef_nrminf
#define mycoef_nrm2 mycoef_nrm2

/* casts */
#define mycoef_to_myfloat mycoef_to_myfloat

/* assign */
#define mycoef_set mycoef_set
#define mycoef_set_zero mycoef_set_zero
#define mycoef_set_myfloat mycoef_set_myfloat
#define mycoef_set_d mycoef_set_d
#define mycoef_set_si mycoef_set_si

/* elemental operations */
#define mycoef_add2 mycoef_add2
#define mycoef_sub2 mycoef_sub2
#define mycoef_mul2 mycoef_mul2
#define mycoef_div2 mycoef_div2

#define mycoef_add2_myfloat mycoef_add2_myfloat
#define mycoef_sub2_myfloat mycoef_sub2_myfloat
#define mycoef_myfloat_sub2 mycoef_myfloat_sub2
#define mycoef_mul2_myfloat mycoef_mul2_myfloat
#define mycoef_div2_myfloat mycoef_div2_myfloat
#define mycoef_myfloat_div2 mycoef_myfloat_div2

#define mycoef_add2_d mycoef_add2_d
#define mycoef_sub2_d mycoef_sub2_d
#define mycoef_mul2_d mycoef_mul2_d
#define mycoef_div2_d mycoef_div2_d
#define mycoef_d_sub2 mycoef_d_sub2
#define mycoef_d_div2 mycoef_d_div2

#define mycoef_add2_si mycoef_add2_si
#define mycoef_sub2_si mycoef_sub2_si
#define mycoef_mul2_si mycoef_mul2_si
#define mycoef_div2_si mycoef_div2_si
#define mycoef_si_sub2 mycoef_si_sub2
#define mycoef_si_div2 mycoef_si_div2

#define mycoef_neg mycoef_neg

/* built-in functions */
#define mycoef_set_sqrt mycoef_set_sqrt
#define mycoef_set_pow_myfloat mycoef_set_pow_myfloat
#define mycoef_set_pow_si mycoef_set_pow_si

#define mycoef_set_sin mycoef_set_sin
#define mycoef_set_cos mycoef_set_cos
#define mycoef_set_tan mycoef_set_tan
#define mycoef_set_atan mycoef_set_atan
#define mycoef_set_exp mycoef_set_exp
#define mycoef_set_log mycoef_set_log
#define mycoef_set_sinh mycoef_set_sinh
#define mycoef_set_cosh mycoef_set_cosh
#define mycoef_set_tanh mycoef_set_tanh
#define mycoef_set_log10 mycoef_set_log10
#define mycoef_set_fabs mycoef_set_fabs

/* castings */
#define mycoef_to_si mycoef_to_si
#define mycoef_to_d mycoef_to_d

/* boolean operations */
#define mycoef_ge mycoef_ge
#define mycoef_gt mycoef_gt
#define mycoef_le mycoef_le
#define mycoef_lt mycoef_lt
#define mycoef_eq mycoef_eq
#define mycoef_neq mycoef_neq

/* output format */
#define mycoef_fprintf mycoef_fprintf

/* input format */
#define mycoef_fscanf mycoef_fscanf

/* string scanf */
#define mycoef_sscanf4 mycoef_sscanf4
#endif /* END my_coef_t */


/* CODE FOR jet_1_t_taylor_rho */
int * jet_1_monomial_counts_taylor_rho(void) {return _jet_1_monomial_counts_taylor_rho_;}
int * jet_1_monomial_offsets_taylor_rho(void) {return _jet_1_monomial_offsets_taylor_rho_;}
#include <stdlib.h>
#include <stdio.h>
#include <math.h>
#include <string.h>



static int jet_1_flag_init_jet_library_taylor_rho=0;
static int jet_1_nsymb_taylor_rho=_NUMBER_OF_MAX_SYMBOLS_;
static myfloat_t jet_1_faux_taylor_rho;
static mycoef_t jet_1_caux_taylor_rho;
#pragma omp threadprivate(jet_1_flag_init_jet_library_taylor_rho,jet_1_faux_taylor_rho,jet_1_caux_taylor_rho)

size_t jet_1_init_taylor_rho(jet_1_ptr_taylor_rho x)
{
	size_t mem=0;
	int k;
	*x = (__typeof__(*x)) malloc((_JET_COEFFICIENTS_COUNT_TOTAL_)*sizeof(**x));
	if (*x == NULL) {
		fprintf(stderr, "not enough memory to allocate %d\n",_JET_COEFFICIENTS_COUNT_TOTAL_);
		exit(1);
	}
	for (k = 0; k < _JET_COEFFICIENTS_COUNT_TOTAL_; k++) {mycoef_init((*x)[k]);}
	mem+= (_JET_COEFFICIENTS_COUNT_TOTAL_)*sizeof(**x);
	return mem;
}

void jet_1_initup2_taylor_rho(int nsymbs, int deg)
{
	if (jet_1_flag_init_jet_library_taylor_rho==1) return;
	if (deg != 1) {
		fprintf(stderr, "%d: Not allowed deg value: %d!=1\n",__LINE__,deg);
		exit(1);
	}
	if (_NUMBER_OF_MAX_SYMBOLS_ < nsymbs) {
		fprintf(stderr, "%d: Not allowed nsymbs value %d<%d\n",__LINE__,_NUMBER_OF_MAX_SYMBOLS_,nsymbs);
		exit(1);
	}
	jet_1_nsymb_taylor_rho = nsymbs;
	mycoef_initup();
	myfloat_init(jet_1_faux_taylor_rho);
	mycoef_init(jet_1_caux_taylor_rho);
	jet_1_flag_init_jet_library_taylor_rho=1;
}

int jet_1_get_num_symbs_taylor_rho(void){return jet_1_nsymb_taylor_rho;}

int jet_1_get_deg_taylor_rho(void){return 1;}

int jet_1_set_num_symbs_taylor_rho(int nsymbs)
{
	int k;
	if (nsymbs > _NUMBER_OF_MAX_SYMBOLS_) {
		fprintf(stderr, "%d: Invalid num. variables %d > %d\n",__LINE__,nsymbs, _NUMBER_OF_MAX_SYMBOLS_);
		exit(1);
	}
	/* WARNING: in case of parallel region required out of the scope */
	k = jet_1_nsymb_taylor_rho;
	jet_1_nsymb_taylor_rho = nsymbs;
	return k;
}

int jet_1_set_deg_taylor_rho(int deg)
{
	fprintf(stderr, "%d: Action not allowed\n",__LINE__);
	exit(1);
	return 0;
}

void jet_1_clean_taylor_rho(jet_1_ptr_taylor_rho x)
{
	int k;
	if (*x == NULL) return;
	for (k = 0; k < _JET_COEFFICIENTS_COUNT_TOTAL_; k++) {mycoef_clean((*x)[k]);}
	free(*x); *x=NULL;
}

void jet_1_cleanup_taylor_rho(void)
{
	if (jet_1_flag_init_jet_library_taylor_rho==0) return;
	mycoef_clean(jet_1_caux_taylor_rho);
	myfloat_clean(jet_1_faux_taylor_rho);
	mycoef_cleanup();
	jet_1_nsymb_taylor_rho = 0;
	jet_1_flag_init_jet_library_taylor_rho=0;
}

void jet_1_set_taylor_rho(jet_1_t_taylor_rho b, jet_1_t_taylor_rho a)
{
	int k;
	for (k = 0; k <= jet_1_nsymb_taylor_rho; k++) {mycoef_set(b[k],a[k]);}
}

void jet_1_set_coef_array_taylor_rho(jet_1_t_taylor_rho b, mycoef_t *a)
{
	int k;
	for (k = 0; k <= jet_1_nsymb_taylor_rho; k++) {mycoef_set(b[k],a[k]);}
	}

void jet_1_set_jet_2_coef_array_taylor_rho(mycoef_t *b, jet_1_t_taylor_rho a)
{
	int k;
	for (k = 0; k <= jet_1_nsymb_taylor_rho; k++) {mycoef_set(b[k],a[k]);}
	}

void jet_1_set_coef_taylor_rho(jet_1_t_taylor_rho b, mycoef_t a)
{
	int k;
	mycoef_set(b[0],a);
	for (k = 1; k <= jet_1_nsymb_taylor_rho; k++) {mycoef_set_zero(b[k]);}
}

void jet_1_set_myfloat_taylor_rho(jet_1_t_taylor_rho b, myfloat_t a)
{
	int k;
	mycoef_set_myfloat(b[0],a);
	for (k = 1; k <= jet_1_nsymb_taylor_rho; k++) {mycoef_set_zero(b[k]);}
}
void jet_1_set_d_taylor_rho(jet_1_t_taylor_rho b, double a)
{
	int k;
	mycoef_set_d(b[0],a);
	for (k = 1; k <= jet_1_nsymb_taylor_rho; k++) {mycoef_set_zero(b[k]);}
}
void jet_1_set_si_taylor_rho(jet_1_t_taylor_rho b, int a)
{
	int k;
	mycoef_set_si(b[0],a);
	for (k = 1; k <= jet_1_nsymb_taylor_rho; k++) {mycoef_set_zero(b[k]);}
}
myfloat_t* jet_1_to_myfloat_taylor_rho(jet_1_t_taylor_rho a) { return mycoef_to_myfloat(a[0]);}

void jet_1_eval_taylor_rho(mycoef_t t[1], jet_1_t_taylor_rho a, myfloat_t s[]) 
{
	int k;
	mycoef_set_zero(*t);
	for (k = 0; k < jet_1_nsymb_taylor_rho; k++) {
		mycoef_mul2_myfloat(jet_1_caux_taylor_rho,a[k+1],s[k]);
		mycoef_add2(*t,*t,jet_1_caux_taylor_rho);
	}
	mycoef_add2(*t,*t,a[0]);
}
void jet_1_nrminf_taylor_rho(myfloat_t nrm[1], jet_1_t_taylor_rho a)
{
	int k;
	/* WARNING initial value for nrm GIVEN!! */
	for (k = 0; k <= jet_1_nsymb_taylor_rho; k++) {
		mycoef_nrminf(&jet_1_faux_taylor_rho,a[k]);
		if (myfloat_lt(*nrm,jet_1_faux_taylor_rho)) {myfloat_set(*nrm,jet_1_faux_taylor_rho);}
	}
}

void jet_1_nrm2_taylor_rho(myfloat_t nrm[1], jet_1_t_taylor_rho a)
{
	int k;
	/* WARNING initial value for nrm GIVEN!! */
	for (k = 0; k <= jet_1_nsymb_taylor_rho; k++) {
		mycoef_nrm2(&jet_1_faux_taylor_rho,a[k]);
		myfloat_add2(*nrm,*nrm,jet_1_faux_taylor_rho);
	}
	myfloat_set_sqrt(*nrm,*nrm);
}

void jet_1_neg_taylor_rho(jet_1_t_taylor_rho b, jet_1_t_taylor_rho a)
{
	int k;
	for (k = 0; k <= jet_1_nsymb_taylor_rho; k++) {mycoef_neg(b[k],a[k]);}
}

void jet_1_add2_taylor_rho(jet_1_t_taylor_rho c, jet_1_t_taylor_rho a, jet_1_t_taylor_rho b)
{
	int k;
	for (k = 0; k <= jet_1_nsymb_taylor_rho; k++) {mycoef_add2(c[k],a[k],b[k]);}
}
void jet_1_sub2_taylor_rho(jet_1_t_taylor_rho c, jet_1_t_taylor_rho a, jet_1_t_taylor_rho b)
{
	int k;
	for (k = 0; k <= jet_1_nsymb_taylor_rho; k++) {mycoef_sub2(c[k],a[k],b[k]);}
}
void jet_1_mul2_taylor_rho(jet_1_t_taylor_rho c, jet_1_t_taylor_rho a, jet_1_t_taylor_rho b)
{
	int k;
	/* c' = a'b + ab' */
	for (k = 1; k <= jet_1_nsymb_taylor_rho; k++) {
		mycoef_mul2(jet_1_caux_taylor_rho,a[k],b[0]);
		mycoef_mul2(c[k],a[0],b[k]);
		mycoef_add2(c[k],c[k],jet_1_caux_taylor_rho);
	}
	mycoef_mul2(c[0],a[0],b[0]);
}
void jet_1_div2_taylor_rho(jet_1_t_taylor_rho c, jet_1_t_taylor_rho a, jet_1_t_taylor_rho b)
{
	int k;
	/* c' = (a' - ab'/b)/b */
	for (k = 1; k <= jet_1_nsymb_taylor_rho; k++) {
		mycoef_set(jet_1_caux_taylor_rho,a[k]);
		mycoef_mul2(c[k],a[0],b[k]);
		mycoef_div2(c[k],c[k],b[0]);
		mycoef_sub2(c[k],jet_1_caux_taylor_rho,c[k]);
		mycoef_div2(c[k],c[k],b[0]);
	}
	mycoef_div2(c[0],a[0],b[0]);
}

void jet_1_add2_coef_taylor_rho(jet_1_t_taylor_rho c, jet_1_t_taylor_rho a, mycoef_t b)
{
	int k;
	mycoef_add2(c[0],a[0],b);
	if (c != a) for (k = 1; k <= jet_1_nsymb_taylor_rho; k++) {mycoef_set(c[k],a[k]);}
}
void jet_1_sub2_coef_taylor_rho(jet_1_t_taylor_rho c, jet_1_t_taylor_rho a, mycoef_t b)
{
	int k;
	mycoef_sub2(c[0],a[0],b);
	if (c != a) for (k = 1; k <= jet_1_nsymb_taylor_rho; k++) {mycoef_set(c[k],a[k]);}
}
void jet_1_coef_sub2_taylor_rho(jet_1_t_taylor_rho c, mycoef_t b, jet_1_t_taylor_rho a)
{
	int k;
	mycoef_sub2(c[0],b,a[0]);
	for (k = 1; k <= jet_1_nsymb_taylor_rho; k++) {mycoef_neg(c[k],a[k]);}
}
void jet_1_mul2_coef_taylor_rho(jet_1_t_taylor_rho c, jet_1_t_taylor_rho a, mycoef_t b)
{
	int k;
	for (k = 0; k <= jet_1_nsymb_taylor_rho; k++) {mycoef_mul2(c[k],a[k],b);}
}
void jet_1_div2_coef_taylor_rho(jet_1_t_taylor_rho c, jet_1_t_taylor_rho a, mycoef_t b)
{
	int k;
	for (k = 0; k <= jet_1_nsymb_taylor_rho; k++) {mycoef_div2(c[k],a[k],b);}
}
void jet_1_coef_div2_taylor_rho(jet_1_t_taylor_rho c, mycoef_t b, jet_1_t_taylor_rho a)
{
	int k;
	mycoef_div2(c[0],b,a[0]);
	mycoef_div2(jet_1_caux_taylor_rho,c[0],a[0]);
	mycoef_neg(jet_1_caux_taylor_rho,jet_1_caux_taylor_rho);
	/* c' = -b(a'/a)/a */
	for (k = 1; k <= jet_1_nsymb_taylor_rho; k++) {mycoef_mul2(c[k],a[k],jet_1_caux_taylor_rho);}
}

void jet_1_add2_myfloat_taylor_rho(jet_1_t_taylor_rho c, jet_1_t_taylor_rho a, myfloat_t b)
{
	int k;
	mycoef_add2_myfloat(c[0],a[0],b);
	if (c != a) for (k = 1; k <= jet_1_nsymb_taylor_rho; k++) {mycoef_set(c[k],a[k]);}
}
void jet_1_sub2_myfloat_taylor_rho(jet_1_t_taylor_rho c, jet_1_t_taylor_rho a, myfloat_t b)
{
	int k;
	mycoef_sub2_myfloat(c[0],a[0],b);
	if (c != a) for (k = 1; k <= jet_1_nsymb_taylor_rho; k++) {mycoef_set(c[k],a[k]);}
}
void jet_1_myfloat_sub2_taylor_rho(jet_1_t_taylor_rho c, myfloat_t b, jet_1_t_taylor_rho a)
{
	int k;
	mycoef_sub2_myfloat (c[0],a[0],b);
	mycoef_neg(c[0],c[0]);
	for (k = 1; k <= jet_1_nsymb_taylor_rho; k++) {mycoef_neg(c[k],a[k]);}
}
void jet_1_mul2_myfloat_taylor_rho(jet_1_t_taylor_rho c, jet_1_t_taylor_rho a, myfloat_t b)
{
	int k;
	for (k = 0; k <= jet_1_nsymb_taylor_rho; k++) {mycoef_mul2_myfloat(c[k],a[k],b);}
}
void jet_1_div2_myfloat_taylor_rho(jet_1_t_taylor_rho c, jet_1_t_taylor_rho a, myfloat_t b)
{
	int k;
	for (k = 0; k <= jet_1_nsymb_taylor_rho; k++) {mycoef_div2_myfloat(c[k],a[k],b);}
}
void jet_1_myfloat_div2_taylor_rho(jet_1_t_taylor_rho c, myfloat_t b, jet_1_t_taylor_rho a)
{
	int k;
	mycoef_myfloat_div2(c[0],b,a[0]);
	mycoef_div2(jet_1_caux_taylor_rho,c[0],a[0]);
	mycoef_neg(jet_1_caux_taylor_rho,jet_1_caux_taylor_rho);
	/* c' = -b(a'/a)/a */
	for (k = 1; k <= jet_1_nsymb_taylor_rho; k++) {mycoef_mul2(c[k],a[k],jet_1_caux_taylor_rho);}
}

void jet_1_add2_d_taylor_rho(jet_1_t_taylor_rho c, jet_1_t_taylor_rho a, double b)
{
	int k;
	mycoef_add2_d(c[0],a[0],b);
	if (c != a) for (k = 1; k <= jet_1_nsymb_taylor_rho; k++) {mycoef_set(c[k],a[k]);}
}
void jet_1_sub2_d_taylor_rho(jet_1_t_taylor_rho c, jet_1_t_taylor_rho a, double b)
{
	int k;
	mycoef_sub2_d(c[0],a[0],b);
	if (c != a) for (k = 1; k <= jet_1_nsymb_taylor_rho; k++) {mycoef_set(c[k],a[k]);}
}
void jet_1_d_sub2_taylor_rho(jet_1_t_taylor_rho c, double b, jet_1_t_taylor_rho a)
{
	int k;
	mycoef_sub2_d (c[0],a[0],b);
	mycoef_neg(c[0],c[0]);
	for (k = 1; k <= jet_1_nsymb_taylor_rho; k++) {mycoef_neg(c[k],a[k]);}
}
void jet_1_mul2_d_taylor_rho(jet_1_t_taylor_rho c, jet_1_t_taylor_rho a, double b)
{
	int k;
	for (k = 0; k <= jet_1_nsymb_taylor_rho; k++) {mycoef_mul2_d(c[k],a[k],b);}
}
void jet_1_div2_d_taylor_rho(jet_1_t_taylor_rho c, jet_1_t_taylor_rho a, double b)
{
	int k;
	for (k = 0; k <= jet_1_nsymb_taylor_rho; k++) {mycoef_div2_d(c[k],a[k],b);}
}
void jet_1_d_div2_taylor_rho(jet_1_t_taylor_rho c, double b, jet_1_t_taylor_rho a)
{
	int k;
	mycoef_d_div2(c[0],b,a[0]);
	mycoef_div2(jet_1_caux_taylor_rho,c[0],a[0]);
	mycoef_neg(jet_1_caux_taylor_rho,jet_1_caux_taylor_rho);
	/* c' = -b(a'/a)/a */
	for (k = 1; k <= jet_1_nsymb_taylor_rho; k++) {mycoef_mul2(c[k],a[k],jet_1_caux_taylor_rho);}
}

void jet_1_add2_si_taylor_rho(jet_1_t_taylor_rho c, jet_1_t_taylor_rho a, int b)
{
	int k;
	mycoef_add2_si(c[0],a[0],b);
	if (c != a) for (k = 1; k <= jet_1_nsymb_taylor_rho; k++) {mycoef_set(c[k],a[k]);}
}
void jet_1_sub2_si_taylor_rho(jet_1_t_taylor_rho c, jet_1_t_taylor_rho a, int b)
{
	int k;
	mycoef_sub2_si(c[0],a[0],b);
	if (c != a) for (k = 1; k <= jet_1_nsymb_taylor_rho; k++) {mycoef_set(c[k],a[k]);}
}
void jet_1_si_sub2_taylor_rho(jet_1_t_taylor_rho c, int b, jet_1_t_taylor_rho a)
{
	int k;
	mycoef_sub2_si(c[0],a[0],b);
	mycoef_neg(c[0],c[0]);
	for (k = 1; k <= jet_1_nsymb_taylor_rho; k++) {mycoef_neg(c[k],a[k]);}
}
void jet_1_mul2_si_taylor_rho(jet_1_t_taylor_rho c, jet_1_t_taylor_rho a, int b)
{
	int k;
	for (k = 0; k <= jet_1_nsymb_taylor_rho; k++) {mycoef_mul2_si(c[k],a[k],b);}
}
void jet_1_div2_si_taylor_rho(jet_1_t_taylor_rho c, jet_1_t_taylor_rho a, int b)
{
	int k;
	for (k = 0; k <= jet_1_nsymb_taylor_rho; k++) {mycoef_div2_si(c[k],a[k],b);}
}
void jet_1_si_div2_taylor_rho(jet_1_t_taylor_rho c, int b, jet_1_t_taylor_rho a)
{
	int k;
	mycoef_si_div2(c[0],b,a[0]);
	mycoef_div2(jet_1_caux_taylor_rho,c[0],a[0]);
	mycoef_neg(jet_1_caux_taylor_rho,jet_1_caux_taylor_rho);
	/* c' = -b(a'/a)/a */
	for (k = 1; k <= jet_1_nsymb_taylor_rho; k++) {mycoef_mul2(c[k],a[k],jet_1_caux_taylor_rho);}
}

void jet_1_set_sqrt_taylor_rho(jet_1_t_taylor_rho s, jet_1_t_taylor_rho a)
{
	int k;
	/* s'=a'/(2s[0]) */
	mycoef_set_sqrt(s[0],a[0]);
	for (k = 1; k <= jet_1_nsymb_taylor_rho; k++) {
		mycoef_div2(s[k],a[k],s[0]);
		mycoef_div2_si(s[k],s[k],2);
	}
}

void jet_1_set_pow_myfloat_taylor_rho(jet_1_t_taylor_rho p, jet_1_t_taylor_rho a, myfloat_t b)
{
	int k;
	myfloat_sub2_si(jet_1_faux_taylor_rho,b,1);
	/* p'= b p[0]/a[0] a' */
	mycoef_set_pow_myfloat(jet_1_caux_taylor_rho,a[0],jet_1_faux_taylor_rho);
	mycoef_mul2_myfloat(jet_1_caux_taylor_rho,jet_1_caux_taylor_rho,b);
	mycoef_set_pow_myfloat(p[0],a[0],b);
	for (k = 1; k <= jet_1_nsymb_taylor_rho; k++) {mycoef_mul2(p[k],a[k],jet_1_caux_taylor_rho);}
}

void jet_1_set_exp_taylor_rho(jet_1_t_taylor_rho e, jet_1_t_taylor_rho a)
{
	int k;
	/* e'=a'e[0] */
	mycoef_set_exp(e[0],a[0]);
	for (k = 1; k <= jet_1_nsymb_taylor_rho; k++) {mycoef_mul2(e[k],e[0],a[k]);}
}
void jet_1_set_log_taylor_rho(jet_1_t_taylor_rho l, jet_1_t_taylor_rho a)
{
	int k;
	/* l'=a'/a[0] */
	for (k = 1; k <= jet_1_nsymb_taylor_rho; k++) {mycoef_div2(l[k],a[k],a[0]);}
	mycoef_set_log(l[0],a[0]);
}

void jet_1_set_sin_taylor_rho(jet_1_t_taylor_rho s, jet_1_t_taylor_rho a)
{
	int k;
	/* s'=cos(a[0])a' */
	mycoef_set_cos(jet_1_caux_taylor_rho,a[0]);
	mycoef_set_sin(s[0],a[0]);
	for (k = 1; k <= jet_1_nsymb_taylor_rho; k++) {mycoef_mul2(s[k],jet_1_caux_taylor_rho,a[k]);}
}
void jet_1_set_cos_taylor_rho(jet_1_t_taylor_rho c, jet_1_t_taylor_rho a)
{
	int k;
	/* c'=-sin(a[0])a' */
	mycoef_set_sin(jet_1_caux_taylor_rho,a[0]);
	mycoef_neg(jet_1_caux_taylor_rho,jet_1_caux_taylor_rho);
	mycoef_set_cos(c[0],a[0]);
	for (k = 1; k <= jet_1_nsymb_taylor_rho; k++) {mycoef_mul2(c[k],jet_1_caux_taylor_rho,a[k]);}
}
void jet_1_set_tan_taylor_rho(jet_1_t_taylor_rho t, jet_1_t_taylor_rho a)
{
	int k;
	/* t'= (1+tan(a[0])^2)a'*/
	mycoef_set_tan(t[0],a[0]);
	mycoef_mul2(jet_1_caux_taylor_rho,t[0],t[0]);
	mycoef_add2_si(jet_1_caux_taylor_rho,jet_1_caux_taylor_rho,1);
	for (k = 1; k <= jet_1_nsymb_taylor_rho; k++) {mycoef_mul2(t[k],a[k],jet_1_caux_taylor_rho);}
}
void jet_1_set_atan_taylor_rho(jet_1_t_taylor_rho t, jet_1_t_taylor_rho a)
{
	int k;
	/* t'= a'/(1+(a[0])^2)*/
	mycoef_set_atan(t[0],a[0]);
	mycoef_mul2(jet_1_caux_taylor_rho,a[0],a[0]);
	mycoef_add2_si(jet_1_caux_taylor_rho,jet_1_caux_taylor_rho,1);
	for (k = 1; k <= jet_1_nsymb_taylor_rho; k++) {mycoef_div2(t[k],a[k],jet_1_caux_taylor_rho);}
}
void jet_1_set_sinh_taylor_rho(jet_1_t_taylor_rho s, jet_1_t_taylor_rho a)
{
	int k;
	/* s'=cosh(a[0])a' */
	mycoef_set_cosh(jet_1_caux_taylor_rho,a[0]);
	mycoef_set_sinh(s[0],a[0]);
	for (k = 1; k <= jet_1_nsymb_taylor_rho; k++) {mycoef_mul2(s[k],jet_1_caux_taylor_rho,a[k]);}
}
void jet_1_set_cosh_taylor_rho(jet_1_t_taylor_rho c, jet_1_t_taylor_rho a)
{
	int k;
	/* c'=sinh(a[0])a' */
	mycoef_set_sinh(jet_1_caux_taylor_rho,a[0]);
	mycoef_set_cosh(c[0],a[0]);
	for (k = 1; k <= jet_1_nsymb_taylor_rho; k++) {mycoef_mul2(c[k],jet_1_caux_taylor_rho,a[k]);}
}
void jet_1_fprintf_taylor_rho(FILE *file, const char *fmt, jet_1_t_taylor_rho a)
{
	int k;
	for (k = 0; k <= jet_1_nsymb_taylor_rho; k++) {		mycoef_fprintf(file,fmt,a[k]);
	}
}
void jet_1_fscanf_taylor_rho(FILE *file, const char *fmt, jet_1_t_taylor_rho a)
{
	int k;
	for (k = 0; k < _JET_COEFFICIENTS_COUNT_TOTAL_; k++) {		mycoef_fscanf(file, fmt, MY_JET_DATA(a,k));
	}
}
static char *jet_1_sscanf4_taylor_rho(char *ptr, const char *myfmt, jet_1_t_taylor_rho a, int *l)
{
	int k;
	for (k = 0; k <_JET_COEFFICIENTS_COUNT_TOTAL_ && *ptr!='\0'; k++){
		ptr = mycoef_sscanf4(ptr, myfmt, MY_JET_DATA(a,k), l);
	}
	for ( ; k <_JET_COEFFICIENTS_COUNT_TOTAL_; k++) {mycoef_set_zero(MY_JET_DATA(a,k));}
	return ptr;
}
void jet_1_sscanf_taylor_rho(const char *str, const char *fmt, jet_1_t_taylor_rho a)
{
	int l;
	const int len=fmt?strnlen(fmt,128):0; /* NOTE: safety string length of 128 */
	char myfmt[len+3], *mystr = strdup(str);
	sprintf(myfmt, "%s%%n",fmt);
	jet_1_sscanf4_taylor_rho(mystr, myfmt, a, &l);
	free(mystr);
}

/* END CODE jet_1_t_taylor_rho */

/***********************************************************************
 *
 * Procedure generated by the TAYLOR translator. Do not edit!
 *
 * It needs the header file 'taylor.h' to compile.
 * Run taylor with the -header -o taylor.h option to generate a sample 'taylor.h'

 * Translation info is at the end of this file.
 * Version 2.1, May 26, 2023
 ***********************************************************************/

#include <stdio.h>
#include <stdlib.h>
MY_FLOAT **taylor_coefficients_taylor_rho_A(MY_FLOAT t, MY_FLOAT *x, int order, int rflag, MY_JET *sIn, MY_JET ***sOut)
{
   /* input: 
      t:     current value of the time variable 
      x:     array represent values of the state variables
      order: order of the taylor coefficients sought
      rflag: recompute flag. If you call this routine with one order 
             first, but then decided that you need a higher order of the
             taylor polynomial, you can pass 0 to rflag. This routine 
             will try to use the values already computed. Provided that 
             both x and t have not been changed, and you did not modify 
             the jet derivatives from the previous call.
      sIn:   array representing the input jet variables
             If NULL, the x values are assigned.
      sOut:  Pointer output jet variables
             If NULL, the pointer is not modified.
      Return Value:
            Two D Array, rows are the taylor coefficients of the
            state variables

     */
    extern MY_FLOAT s;
    extern MY_FLOAT w;
    extern MY_FLOAT q;
    extern MY_FLOAT fff;

    static MY_FLOAT     *_jz_jet[17],  *_jz_save = NULL, *_jz_oneOverN=NULL,*_jz_theNs=NULL;
    static MY_FLOAT     _jz_tvar1, _jz_tvar2, _jz_tvar3, _jz_tvar4; /* tmp vars */
    static MY_FLOAT     _jz_uvar1, _jz_uvar2; /* tmp vars */
    static MY_FLOAT     _jz_svar1, _jz_svar2, _jz_svar3, _jz_svar4, _jz_svar5; /* tmp vars */
    static MY_FLOAT     _jz_wvar3, _jz_wvar4; /* tmp vars */
    static MY_FLOAT     _jz_zvar1, _jz_zvar2; /* tmp vars */
    static MY_FLOAT     _jz_MyFloatZERO, _kthtmp;
    #pragma omp threadprivate(_jz_jet, _jz_save, _jz_oneOverN, _jz_theNs, _jz_tvar1, _jz_tvar2, _jz_tvar3, _jz_tvar4, _jz_uvar1, _jz_uvar2, _jz_svar1, _jz_svar2, _jz_svar3, _jz_svar4, _jz_svar5, _jz_wvar3, _jz_wvar4, _jz_zvar1, _jz_zvar2, _jz_MyFloatZERO, _kthtmp)
/* series bgn */
    static MY_JET       *_sjz_jet[17], *_sjz_save = NULL;
    static MY_JET     _sjz_tvar1, _sjz_tvar2, _sjz_tvar3, _sjz_tvar4; /* tmp vars */
    static MY_JET     _sjz_uvar1, _sjz_uvar2; /* tmp vars */
    static MY_JET     _sjz_svar1, _sjz_svar2, _sjz_svar3, _sjz_svar4, _sjz_svar5; /* tmp vars */
    static MY_JET     _sjz_wvar3, _sjz_wvar4; /* tmp vars */
    static MY_JET     _sjz_zvar1, _sjz_zvar2; /* tmp vars */
    static MY_JET     _kthStmp; /* tmp vars */
    #pragma omp threadprivate(_sjz_jet, _sjz_save, _sjz_tvar1, _sjz_tvar2, _sjz_tvar3, _sjz_tvar4, _sjz_uvar1, _sjz_uvar2, _sjz_svar1, _sjz_svar2, _sjz_svar3, _sjz_svar4, _sjz_svar5,  _sjz_wvar3, _sjz_wvar4, _sjz_zvar1, _sjz_zvar2, _kthStmp)
/* series end */
    static int          _jz_maxOrderUsed  = -1;
    static int          _jz_lastOrder = 0, _jz_initialized=0, _jz_ginitialized=0;
    int                 _jz_i, _jz_j, _jz_k, _jz_l, _jz_m, _jz_n, _jz_oorder ;
    #pragma omp threadprivate(_jz_maxOrderUsed,_jz_lastOrder, _jz_initialized, _jz_ginitialized)
    /* allocating memory if needed */
    if (_jz_maxOrderUsed < order )  { 
    	 if (_jz_ginitialized == 0) { 
    	   InitMyFloat(_jz_tvar1); InitMyFloat(_jz_tvar2);InitMyFloat(_jz_tvar3);InitMyFloat(_jz_tvar4);
    	   InitMyFloat(_jz_svar1); InitMyFloat(_jz_svar2);InitMyFloat(_jz_svar3);InitMyFloat(_jz_svar4);
    	   InitMyFloat(_jz_svar5); InitMyFloat(_jz_zvar1);InitMyFloat(_jz_zvar2);
    	   InitMyFloat(_jz_uvar1); InitMyFloat(_jz_uvar2);
    	   InitMyFloat(_jz_wvar3);InitMyFloat(_jz_wvar4);
    	   InitMyFloat(_jz_MyFloatZERO); InitMyFloat(_kthtmp);
    	   MakeMyFloatC(_jz_MyFloatZERO, "0", (double)0);
    	   /* series bgn */
    	   InitJet(_sjz_tvar1); InitJet(_sjz_tvar2);InitJet(_sjz_tvar3);InitJet(_sjz_tvar4);
    	   InitJet(_sjz_svar1); InitJet(_sjz_svar2);InitJet(_sjz_svar3);InitJet(_sjz_svar4);
    	   InitJet(_sjz_svar5); InitJet(_sjz_zvar1);InitJet(_sjz_zvar2);
    	   InitJet(_sjz_uvar1); InitJet(_sjz_uvar2);
    	   InitJet(_sjz_wvar3); InitJet(_sjz_wvar4);
    	   InitJet(_kthStmp);
    	   /* series end */
    	 }
    	 if (rflag > 0) rflag = 0; /* have to recompute everything */
    	 _jz_oorder=_jz_maxOrderUsed;
    	 _jz_maxOrderUsed  = order;
    	 if (_jz_ginitialized) { 
    	   for(_jz_i=0; _jz_i< _jz_oorder+1; _jz_i++) {ClearMyFloat(_jz_oneOverN[_jz_i]); ClearMyFloat(_jz_theNs[_jz_i]);}
    	   free(_jz_oneOverN); free(_jz_theNs);
    	 }
    	 _jz_theNs = (MY_FLOAT *)malloc((order+1) * sizeof(MY_FLOAT));
    	 _jz_oneOverN = (MY_FLOAT *)malloc((order+1) * sizeof(MY_FLOAT));
    	 for(_jz_i=0; _jz_i<order+1; _jz_i++) {InitMyFloat(_jz_oneOverN[_jz_i]);InitMyFloat(_jz_theNs[_jz_i]);}
    	 MakeMyFloatC(_jz_theNs[0],"0.0", (double)0.0);
    	 MakeMyFloatC(_jz_uvar1,"1.0", (double)1.0);
    	 for(_jz_i = 1; _jz_i <= order; _jz_i++) {
    		 AssignMyFloat(_jz_tvar2, _jz_theNs[_jz_i-1]);
    		 AddMyFloatA(_jz_theNs[_jz_i], _jz_tvar2, _jz_uvar1);
	}
    	 AssignMyFloat(_jz_oneOverN[0],_jz_uvar1);
    	 AssignMyFloat(_jz_oneOverN[1],_jz_uvar1);
    	 for(_jz_i = 2; _jz_i <= order; _jz_i++) {
    		 DivideMyFloatA(_jz_oneOverN[_jz_i], _jz_uvar1,_jz_theNs[_jz_i]);
	}
    	 if (_jz_ginitialized) {
    	    for(_jz_i=0; _jz_i<(_jz_oorder+1)*(17); _jz_i++) { ClearMyFloat(_jz_save[_jz_i]);} free(_jz_save);
	  /* series bgn */
    	    for(_jz_i=0; _jz_i<(_jz_oorder+1)*(17); _jz_i++) { ClearJet(_sjz_save[_jz_i]);} free(_sjz_save);
	  /* series end */
    	 }
    	 _jz_save = (MY_FLOAT *)malloc((order+1)* 17 *sizeof(MY_FLOAT));
    	 for(_jz_i=0; _jz_i<(order+1)*(17); _jz_i++) { InitMyFloat(_jz_save[_jz_i]);}
    	 for(_jz_j = 0, _jz_k = 0; _jz_j < 17 ;  _jz_j++, _jz_k += order+1) { _jz_jet[_jz_j] =& (_jz_save[_jz_k]); }
    	 /*s eries bgn */
    	 _sjz_save = (MY_JET *)malloc((order+1)* 17 *sizeof(MY_JET));
    	 for(_jz_i=0; _jz_i<(order+1)*(17); _jz_i++) { InitJet(_sjz_save[_jz_i]);}
    	 for(_jz_j = 0, _jz_k = 0; _jz_j < 17 ;  _jz_j++, _jz_k += order+1) { _sjz_jet[_jz_j] =& (_sjz_save[_jz_k]); }
    	 /* series end */

    	 /* True constants, initialized only once. */
    }

    if (rflag) {
    	 if (rflag < 0 ) return(NULL);
    	 for(_jz_i = 0; rflag != 0 && _jz_i < 3; _jz_i++) {
    		 if (MyFloatA_NEQ_B(_jz_jet[_jz_i][0], x[_jz_i])) rflag = 0;
    	 }
    }

    if (rflag == 0) {
	 /* initialize all constant vars and state variables */
	 _jz_lastOrder = 1;
		 /* init state variable: */
	 AssignFloatToJet(_sjz_jet[0][0], x[0]);
	 AssignMyFloat(_jz_jet[0][0], x[0]);
		 /* init state variable: */
	 AssignFloatToJet(_sjz_jet[1][0], x[1]);
	 AssignMyFloat(_jz_jet[1][0], x[1]);
		 /* init state variable: */
	 AssignFloatToJet(_sjz_jet[2][0], x[2]);
	 AssignMyFloat(_jz_jet[2][0], x[2]);
/* series bgn */
	 if (sIn){
		 AssignJetToJet(_sjz_jet[0][0], sIn[0]);
		 AssignJetToFloat(_jz_jet[0][0], sIn[0]);
		 AssignJetToJet(_sjz_jet[1][0], sIn[1]);
		 AssignJetToFloat(_jz_jet[1][0], sIn[1]);
		 AssignJetToJet(_sjz_jet[2][0], sIn[2]);
		 AssignJetToFloat(_jz_jet[2][0], sIn[2]);
	 }
/* series end */
	 /* mult: v_011=(v_004*v_005) */
	 MultiplyJetJetA(_sjz_jet[3][0], _sjz_jet[0][0], _sjz_jet[1][0]);
	 /* minus: v_012=(v_005-v_011) */
	 SubtractJetJetA(_sjz_jet[4][0], _sjz_jet[1][0], _sjz_jet[3][0]);
	 /* plus: v_013=(v_004+v_012) */
	 AddJetJetA(_sjz_jet[5][0], _sjz_jet[0][0], _sjz_jet[4][0]);
	 /* mult: v_014=(q*v_004) */
	 MultiplyFloatJetA(_sjz_jet[6][0], q, _sjz_jet[0][0]);
	 /* mult: v_015=(v_004*v_014) */
	 MultiplyJetJetA(_sjz_jet[7][0], _sjz_jet[0][0], _sjz_jet[6][0]);
	 /* minus: v_016=(v_013-v_015) */
	 SubtractJetJetA(_sjz_jet[8][0], _sjz_jet[5][0], _sjz_jet[7][0]);
	 /* mult: v_017=(s*v_016) */
	 MultiplyFloatJetA(_sjz_jet[9][0], s, _sjz_jet[8][0]);
	 /* negate: v_018=(-v_005) */
	 NegateJetA(_sjz_jet[10][0],_sjz_jet[1][0]);
	 /* minus: v_020=(v_018-v_011) */
	 SubtractJetJetA(_sjz_jet[11][0], _sjz_jet[10][0], _sjz_jet[3][0]);
	 /* mult: v_021=(fff*v_006) */
	 MultiplyFloatJetA(_sjz_jet[12][0], fff, _sjz_jet[2][0]);
	 /* plus: v_022=(v_020+v_021) */
	 AddJetJetA(_sjz_jet[13][0], _sjz_jet[11][0], _sjz_jet[12][0]);
	 /* div: v_023=(v_022/s) */
	 DivideJetFloatA(_sjz_jet[14][0], _sjz_jet[13][0], s);
	 /* minus: v_024=(v_004-v_006) */
	 SubtractJetJetA(_sjz_jet[15][0], _sjz_jet[0][0], _sjz_jet[2][0]);
	 /* mult: v_025=(v_024*w) */
	 MultiplyJetFloatA(_sjz_jet[16][0], _sjz_jet[15][0], w);

	 /* the first derivative of state variables */
	 /* state variable 0: */
	 AssignJetToJet(_sjz_jet[0][1], _sjz_jet[9][0]);
	 AssignJetToFloat(_jz_jet[0][1], _sjz_jet[0][1]);
	 /* state variable 1: */
	 AssignJetToJet(_sjz_jet[1][1], _sjz_jet[14][0]);
	 AssignJetToFloat(_jz_jet[1][1], _sjz_jet[1][1]);
	 /* state variable 2: */
	 AssignJetToJet(_sjz_jet[2][1], _sjz_jet[16][0]);
	 AssignJetToFloat(_jz_jet[2][1], _sjz_jet[2][1]);
	}

	 /* compute the kth order derivatives of all vars */
	 for(_jz_k = _jz_lastOrder; _jz_k < order; _jz_k++) {
		 /* derivative for tmp variables */
		 /* mult: v_011=(v_004*v_005) */
		 { /* multiplication */
			 static MY_FLOAT tmp1, tmp2, tmp;
			 #pragma omp threadprivate(tmp1, tmp2, tmp)
			 static MY_JET stmp1, stmp2, stmp;
			 #pragma omp threadprivate(stmp1, stmp2, stmp)
			 if(_jz_initialized==0) {
			   InitMyFloat(tmp1);InitMyFloat(tmp2); InitMyFloat(tmp);
			   InitJet(stmp1);InitJet(stmp2); InitJet(stmp);
			   }
			 AssignFloatToJet(stmp, _jz_MyFloatZERO);
			 for(_jz_l=0; _jz_l<=_jz_k; _jz_l++) {
			     MultiplyJetJetA(stmp1, _sjz_jet[0][_jz_l], _sjz_jet[1][_jz_k-_jz_l]);
			     AssignJetToJet(stmp2, stmp);
			     AddJetJetA(stmp, stmp2, stmp1);
			 }
			 AssignJetToJet(_sjz_jet[3][_jz_k], stmp);
		 }
		 /* minus: v_012=(v_005-v_011) */
		 SubtractJetJetA(_sjz_jet[4][_jz_k], _sjz_jet[1][_jz_k],_sjz_jet[3][_jz_k]);
		 /* plus: v_013=(v_004+v_012) */
		 AddJetJetA(_sjz_jet[5][_jz_k], _sjz_jet[0][_jz_k],_sjz_jet[4][_jz_k]);
		 /* mult: v_014=(q*v_004) */
		 MultiplyFloatJetA(_sjz_jet[6][_jz_k], q, _sjz_jet[0][_jz_k]);
		 /* mult: v_015=(v_004*v_014) */
		 { /* multiplication */
			 static MY_FLOAT tmp1, tmp2, tmp;
			 #pragma omp threadprivate(tmp1, tmp2, tmp)
			 static MY_JET stmp1, stmp2, stmp;
			 #pragma omp threadprivate(stmp1, stmp2, stmp)
			 if(_jz_initialized==0) {
			   InitMyFloat(tmp1);InitMyFloat(tmp2); InitMyFloat(tmp);
			   InitJet(stmp1);InitJet(stmp2); InitJet(stmp);
			   }
			 AssignFloatToJet(stmp, _jz_MyFloatZERO);
			 for(_jz_l=0; _jz_l<=_jz_k; _jz_l++) {
			     MultiplyJetJetA(stmp1, _sjz_jet[0][_jz_l], _sjz_jet[6][_jz_k-_jz_l]);
			     AssignJetToJet(stmp2, stmp);
			     AddJetJetA(stmp, stmp2, stmp1);
			 }
			 AssignJetToJet(_sjz_jet[7][_jz_k], stmp);
		 }
		 /* minus: v_016=(v_013-v_015) */
		 SubtractJetJetA(_sjz_jet[8][_jz_k], _sjz_jet[5][_jz_k],_sjz_jet[7][_jz_k]);
		 /* mult: v_017=(s*v_016) */
		 MultiplyFloatJetA(_sjz_jet[9][_jz_k], s, _sjz_jet[8][_jz_k]);
		 /* negation: v_018=(-v_005) */
		 NegateJetA(_sjz_jet[10][_jz_k], _sjz_jet[1][_jz_k]);
		 /* minus: v_020=(v_018-v_011) */
		 SubtractJetJetA(_sjz_jet[11][_jz_k], _sjz_jet[10][_jz_k],_sjz_jet[3][_jz_k]);
		 /* mult: v_021=(fff*v_006) */
		 MultiplyFloatJetA(_sjz_jet[12][_jz_k], fff, _sjz_jet[2][_jz_k]);
		 /* plus: v_022=(v_020+v_021) */
		 AddJetJetA(_sjz_jet[13][_jz_k], _sjz_jet[11][_jz_k],_sjz_jet[12][_jz_k]);
		 /* div: v_023=(v_022/s) */
		 DivideJetFloatA(_sjz_jet[14][_jz_k], _sjz_jet[13][_jz_k], s);
		 /* minus: v_024=(v_004-v_006) */
		 SubtractJetJetA(_sjz_jet[15][_jz_k], _sjz_jet[0][_jz_k],_sjz_jet[2][_jz_k]);
		 /* mult: v_025=(v_024*w) */
		 MultiplyJetFloatA(_sjz_jet[16][_jz_k], _sjz_jet[15][_jz_k], w);
		 /* derivative of state variables */
		 _jz_m = _jz_k+1;
		 /* state variable 0: */
		 DivideJetFloatA(_sjz_jet[0][_jz_m], _sjz_jet[9][_jz_k], _jz_theNs[_jz_m]);
		 AssignJetToFloat(_jz_jet[0][_jz_m], _sjz_jet[0][_jz_m]);
		 /* state variable 1: */
		 DivideJetFloatA(_sjz_jet[1][_jz_m], _sjz_jet[14][_jz_k], _jz_theNs[_jz_m]);
		 AssignJetToFloat(_jz_jet[1][_jz_m], _sjz_jet[1][_jz_m]);
		 /* state variable 2: */
		 DivideJetFloatA(_sjz_jet[2][_jz_m], _sjz_jet[16][_jz_k], _jz_theNs[_jz_m]);
		 AssignJetToFloat(_jz_jet[2][_jz_m], _sjz_jet[2][_jz_m]);
		 _jz_initialized=1;
	 }
    _jz_lastOrder = order;
    _jz_ginitialized=1;
    if (sOut) {
     *sOut = _sjz_jet;
    }
    return(_jz_jet);
}

MY_FLOAT **taylor_coefficients_taylor_rhoA(MY_FLOAT t, MY_FLOAT *x, int order, int rflag)
{
    return(taylor_coefficients_taylor_rho_A(t,x,order,rflag, NULL, NULL));
}

MY_FLOAT **taylor_coefficients_taylor_rho(MY_FLOAT t, MY_FLOAT *x, int order)
{
    return(taylor_coefficients_taylor_rhoA(t,x,order,0));
}

